### ISSUE TITLE
原版的dubbo-php-framework可以自动获取zookeeper dubbo节点里面的注册服务直接调用,当前改良版如何自动获取?

### ISSUE THREAD

**Issue by io3x** [crazyxman/dubbo-php-framework#3]
如com.fenqile.example.DemoService
报错
Fatal error: Uncaught Dubbo\Common\DubboException: Unable to find 'com.fenqile.example.DemoService' service in configuration file in /home/www/dubbo-php-framework-crazyxman/src/rpc/Consumer/DubboConsumer.php:54

**Comment by crazyxman** [comment]
com.fenqile.example.DemoService 这个服务没有在配置文件 ConsumerConfig.yaml 中定义

**Comment by chenyu99413** [comment]
我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗
PHP Fatal error:  Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68
Stack trace:
#0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....')
#1 {main}
  thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68

**Comment by andy521** [comment]
> 我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗 PHP Fatal error: Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68 Stack trace: #0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....') #1 {main} thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68

这个最后解决了吗？

**Comment by wufengzhicheng** [comment]
> > 我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗 PHP Fatal error: Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68 Stack trace: #0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....') #1 {main} thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68
> 
> 这个最后解决了吗？

解决了

**Comment by andy521** [comment]
> > > 我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗 PHP Fatal error: Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68 Stack trace: #0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....') #1 {main} thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68
> > 
> > 
> > 这个最后解决了吗？
> 
> 解决了

您好，大概是怎么解决的呢？是配置问题？可以php 调通java 提供的provider吗？

**Comment by wufengzhicheng** [comment]
> > > > 我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗 PHP Fatal error: Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68 Stack trace: #0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....') #1 {main} thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68
> > > 
> > > 
> > > 这个最后解决了吗？
> > 
> > 
> > 解决了
> 
> 您好，大概是怎么解决的呢？是配置问题？可以php 调通java 提供的provider吗？

后面改用 https://github.com/dubbo/php-framework-for-apache-dubbo/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B    原版了

**Comment by andy521** [comment]
> > > > > 我用的是测试用例，也报这个错误，ConsumerConfig.yaml没有改动过，这个是说我那个服务没注册成功吗 PHP Fatal error: Uncaught Dubbo\Common\DubboException: No 'php.dubbo.demo.DemoService' provider found in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php:68 Stack trace: #0 /www/dubbo-php-framework-master3/dubbo-php-framework-master/demo/Consumer.php(27): Dubbo\Consumer\DubboConsumer->loadService('php.dubbo.demo....') #1 {main} thrown in /www/dubbo-php-framework-master3/dubbo-php-framework-master/src/rpc/Consumer/DubboConsumer.php on line 68
> > > > 
> > > > 
> > > > 这个最后解决了吗？
> > > 
> > > 
> > > 解决了
> > 
> > 
> > 您好，大概是怎么解决的呢？是配置问题？可以php 调通java 提供的provider吗？
> 
> 后面改用 https://github.com/dubbo/php-framework-for-apache-dubbo/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B 原版了

用原版的话，需要对已有代码改动哪些地方？
